# Official documentation at http://goreleaser.com
project_name: md-exec
builds:
  - env:
      - CGO_ENABLED=0
    binary: mde
    goarch:
      - amd64
    goos:
      - windows
      - linux
      - darwin
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm
    ldflags:
      - -w
      - -s
      - -X github.com/linuxsuren/md-exec/cli.version={{.Version}}
dist: release
archives:
  - name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: amd64
      arm64: arm64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next-{{.ShortCommit}}"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
