name: Pull Request Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
        id: go
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4.1.1
        with:
          github_token: ${{ secrets.GH_PUBLISH_SECRETS }}
          version: v1.14.0
          args: release --skip-publish --rm-dist --snapshot
